# Notas

Numpy

## Crear matrices

In [2]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

## Inspeccionar tu matriz

a.shape -> dimensiones

len(a) -> length

a.ndis -> number of array dimensiones

a.size -> number of array elements

a.dtype -> data type de los elementos

a.dtype.name -> name of data type

a.astype(int) -> convertir el array a un número entero

## Ejercicio

In [7]:
import numpy as np

In [14]:
a = np.random.rand(3,4) # Matriz con números aleatorios entre 0 y 1
a

array([[0.69434974, 0.42758626, 0.90130591, 0.94370272],
       [0.25610983, 0.9474769 , 0.11515308, 0.122896  ],
       [0.11963602, 0.14787269, 0.8848143 , 0.38105088]])

In [16]:
b=a.T # Trasponer
b

array([[0.69434974, 0.25610983, 0.11963602],
       [0.42758626, 0.9474769 , 0.14787269],
       [0.90130591, 0.11515308, 0.8848143 ],
       [0.94370272, 0.122896  , 0.38105088]])

In [18]:
c = b.reshape(2,6) # Reshape
c

array([[0.69434974, 0.25610983, 0.11963602, 0.42758626, 0.9474769 ,
        0.14787269],
       [0.90130591, 0.11515308, 0.8848143 , 0.94370272, 0.122896  ,
        0.38105088]])

In [20]:
d = np.sum(c, axis=1) # Row-wise sum
d

array([2.59303144, 3.34892289])

In [27]:
e = b[b < 0.5] # Filtrar menores a 0,5
e

array([0.25610983, 0.11963602, 0.42758626, 0.14787269, 0.11515308,
       0.122896  , 0.38105088])

In [22]:
# Espaciado: 20 números entre 3 y 5
f = np.linspace(3, 5, 20)
f

array([3.        , 3.10526316, 3.21052632, 3.31578947, 3.42105263,
       3.52631579, 3.63157895, 3.73684211, 3.84210526, 3.94736842,
       4.05263158, 4.15789474, 4.26315789, 4.36842105, 4.47368421,
       4.57894737, 4.68421053, 4.78947368, 4.89473684, 5.        ])

## Pandas